name: Deploy and Test MinIO

description: 'Deploy MinIO and run tests against it'

inputs:
  minio_access_key:
    description: 'MinIO access key'
    required: true
  minio_secret_key:
    description: 'MinIO secret key'
    required: true
  minio_url:
    description: 'MinIO URL'
    required: true
    default: 'http://minio:9000'

runs:
  using: 'docker'
  image: 'docker://minio/minio:latest'  # Correct format for Docker image
  args:
    - |
      # Start the MinIO container
      docker run -d --name minio -p 9000:9000 -p 9001:9001 \
        -e "MINIO_ACCESS_KEY=${{ inputs.minio_access_key }}" \
        -e "MINIO_SECRET_KEY=${{ inputs.minio_secret_key }}" \
        min
