stages:
  - setup
  - test

services:
  - name: minio/minio
    alias: minio
    entrypoint:
      - "minio"
      - "server"
      - "/data"
    command:
      - "--console-address"
      - ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

# Define environment variables to interact with MinIO
variables:
  MINIO_ACCESS_KEY: "rootroot"
  MINIO_SECRET_KEY: "rootroot"
  MINIO_URL: "http://minio:9000"
  MINIO_CONSOLE_URL: "http://minio:9001"


setup_minio:
  stage: setup
  script:
    - echo "MinIO setup completed."
  only:
    - main

run_tests:
  stage: test
  script:
    - curl -X "GET" "$MINIO_URL/minio/health/live"
    - curl -X "GET" "$MINIO_URL/minio/health/ready"
    - echo "Running test against MinIO server"
  only:
    - main
