name: "Text to PNG"
description: "Convert a Text File (eg. command output) to png"
inputs:
  file_location:
    description: 'file containing command output'
    required: true
  archive_file:
    description: 'should archive the png file'
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: "Setup Go"
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: "Convert file"
      shell: 'script --return --quiet --command "bash {0}"'
      run: |
        file_path=$(readlink -f ${{ inputs.file_location }})
        echo "FILE_PATH=$(echo $path)" >> $GITHUB_ENV
        echo "FILENAME=$(basename $path)" >> $GITHUB_ENV
        mkdir file-to-image
        cd file-to-image
        wget https://github.com/ansilove/ansigo/archive/refs/heads/master.zip
        unzip master.zip
        cd ansigo-master
        GO111MODULE=off go build ./...
        mv ansigo-master ../ansigo
        cd ../
        rm -rf file-to-image
        ./ansigo $file_path

    - name: "Archive file"
      if: ${{ inputs.archive_file == 'true' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.FILENAME }}.png
        path: |
          ${{ env.FILE_PATH }}.png