name: Run cypress tests for web-app against network
description: Points cypress to a network and runs tests
inputs:
  web-app-name:
    description: 'web-app to run cypress tests for. Example: bolt'
  app-url:
    description: 'app url for cypress to point to, example: vult.dev-1.devnet-0chain.net'
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Point to dev-* webapp
      shell: 'script --return --quiet --command "bash {0}"'
      run: |
        cd web-apps
        sed "s,baseUrl:.*,baseUrl: 'https:\/\/${{ inputs.app-url }}'," -i packages/test/${{ inputs.web-app-name }}.cypress.config.js
        cat packages/test/${{ inputs.web-app-name }}.cypress.config.js

    - name: Install node.
      shell: 'script --return --quiet --command "bash {0}"'
      run: |
        curl -sL https://deb.nodesource.com/setup_16.x -o /tmp/nodesource_setup.sh
        sudo bash /tmp/nodesource_setup.sh
        sudo apt install nodejs
        node -v

    - name: Install yarn
      shell: 'script --return --quiet --command "bash {0}"'
      run: |
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/yarn.gpg
        echo "deb [signed-by=/etc/apt/trusted.gpg.d/yarn.gpg] https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        sudo apt update
        sudo apt install yarn -y
        yarn --version

    - name: Install yarn
      shell: 'script --return --quiet --command "bash {0}"'
      run: |
        sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y

    - name: Cypress build
      shell: 'script --return --quiet --command "bash {0}"'
      run: |
        cd web-apps
        yarn install --frozen-lockfile --force
        cd packages/test/
        yarn install --frozen-lockfile --force

    - name: Cypress run
      shell: 'script --return --quiet --command "bash {0}"'
      run: |
        cd web-apps
        yarn workspace test cypress:${{ inputs.web-app-name }}:run

