name: "Resolve repo snapshot branches"
description: "Resolve repo snapshot to a list of branches and tags"
inputs:
  repo_snapshots_branch:
    description: 'repo snapshots branch which the tests will use'
    default: 'master'
    required: true
  svc_account_secret:
    description: 'service account secret used to clone repo snapshots'
    default: ""
    required: true
  resolve_images:
    description: 'resolve images for the given feature branches'
    default: "false"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Checkout repo-snapshots"
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.repo_snapshots_branch }}
        repository: 0chain/repo-snapshots
        fetch-depth: 1
        path: ./repo-snapshots
        token: "${{ inputs.svc_account_secret }}"

    - name: "Resolve branches"
      shell: 'script --return --quiet --command "bash {0}"'
      if: ${{ env.SKIP_TESTS != 'true' }}
      run: |
        cd ./repo-snapshots
        while IFS= read -r output; do     echo "$output" >> $GITHUB_ENV; done < <(jq -r 'to_entries[] | select(.value.defaultBranch != null) | "SNAPSHOT_BRANCH_\(.key | ascii_upcase)=\(.value.defaultBranch)"' "branches.json")
        while IFS= read -r output; do     echo "$output" >> $GITHUB_ENV; done < <(jq -r 'to_entries[] | select(.value.sprintBranch != null) | "SNAPSHOT_BRANCH_\(.key | ascii_upcase)=\(.value.sprintBranch)"' "branches.json")

    - name: "Get docker images for sprint branches"
      id: get-images
      if: ${{ inputs.resolve_images == 'true' }}
      uses: 0chain/actions/get-latest-image-for-branch@feature/add-repo-snapshots-integration
      with:
        miner_sharder_branch: ${{ env.SNAPSHOT_BRANCH_0CHAIN }}
        blobber_validator_branch: ${{ env.SNAPSHOT_BRANCH_BLOBBER }}
        authorizer_branch: ${{ env.SNAPSHOT_BRANCH_TOKEN_BRIDGE_AUTHSERVER }}
        zbox_branch: ${{ env.SNAPSHOT_BRANCH_0BOX }}
        zdns_branch: ${{ env.SNAPSHOT_BRANCH_0DNS }}
        svc_account_secret: ${{ inputs.svc_account_secret }}

    - name: "Create variables"
      if: ${{ inputs.resolve_images == 'true' }}
      shell: 'script --return --quiet --command "bash {0}"'
      run: |
        if [[ -n "${{ steps.get-images.outputs.miner-tag }}" ]];then
            echo "SNAPSHOT_BRANCH_MINER_TAG=$(echo '${{ steps.get-images.outputs.miner-tag }}')" >> $GITHUB_ENV
        fi
        
        if [[ -n "${{ steps.get-images.outputs.sharder-tag }}" ]];then
            echo "SNAPSHOT_BRANCH_SHARDER_TAG=$(echo '${{ steps.get-images.outputs.sharder-tag }}')" >> $GITHUB_ENV
        fi
      
        
        if [[ -n "${{ steps.get-images.outputs.blobber-tag }}" ]];then
            echo "SNAPSHOT_BRANCH_BLOBBER_TAG=$(echo '${{ steps.get-images.outputs.blobber-tag }}')" >> $GITHUB_ENV
        fi
        
        if [[ -n "${{ steps.get-images.outputs.validator-tag }}" ]];then
            echo "SNAPSHOT_BRANCH_VALIDATOR_TAG=$(echo '${{ steps.get-images.outputs.validator-tag }}')" >> $GITHUB_ENV
        fi
        
        if [[ -n "${{ steps.get-images.outputs.authorizer-tag }}" ]];then
            echo "SNAPSHOT_BRANCH_AUTHORIZER_TAG=$(echo '${{ steps.get-images.outputs.authorizer-tag }}')" >> $GITHUB_ENV
        fi
        
        if [[ -n "${{ steps.get-images.outputs.zbox-tag }}" ]];then
            echo "SNAPSHOT_BRANCH_ZBOX_TAG=$(echo '${{ steps.get-images.outputs.zbox-tag }}')" >> $GITHUB_ENV
        fi
        
        if [[ -n "$ZDNS_TAG" ]];then
            echo "SNAPSHOT_BRANCH_ZDNS_TAG=$(echo '${{ steps.get-images.outputs.zdns-tag }}')" >> $GITHUB_ENV
        fi
