name: "0Chain System Tests"

concurrency:
  group: "manual-system-tests-${{ github.ref }}"
  cancel-in-progress: true

on:
  workflow_call:
    secrets:
      SVC_ACCOUNT_SECRET:
        description: 'A token used for cross-repo actions'
        required: true
      DEV1KC:
        description: 'dev-1 k8s config'
        required: true
      DEV2KC:
        description: 'dev-2 k8s config'
        required: true
      DEV3KC:
        description: 'dev-3 k8s config'
        required: true
      DEV4KC:
        description: 'dev-4 k8s config'
        required: true
      DEV5KC:
        description: 'dev-5 k8s config'
        required: true
      SMART_CONTRACT_OWNER_WALLET_JSON:
        description: 'Smart contract owner wallet'
        required: true
    inputs:
       system_tests_branch:
        description: 'system_tests branch containing the tests you wish to run'
        default: 'master'
        required: true
        type: string
       miner_branch:
         description: 'miner branch which the tests will use'
         default: 'staging'
         required: false
         type: string
       sharder_branch:
         description: 'sharder branch which the tests will use'
         default: 'staging'
         required: false
         type: string
       zbox_cli_branch:
        description: '0Box CLI branch which the tests will use'
        default: 'staging'
        required: false
        type: string
       zwallet_cli_branch:
        description: '0Wallet CLI branch which the tests will use'
        default: 'staging'
        required: false
        type: string
       blobber_branch:
        description: 'blobber branch to deploy'
        default: 'staging'
        required: false
        type: string
       validator_branch:
        description: 'validator branch to deploy'
        default: 'staging'
        required: false
        type: string
       authorizer_branch:
         description: 'authorizer branch to deploy'
         default: 'staging'
         required: false
         type: string
       zbox_branch:
        description: '0box branch to deploy'
        default: 'staging'
        required: false
        type: string
       zblock_branch:
        description: '0block branch to deploy'
        default: 'staging'
        required: false
        type: string
       zdns_branch:
         description: '0dns branch to deploy'
         default: 'staging'
         required: false
         type: string
       explorer_branch:
         description: 'explorer branch to deploy'
         default: 'staging'
         required: false
         type: string
       zproxy_branch:
         description: '0proxy branch to deploy'
         default: 'staging'
         required: false
         type: string
       zsearch_branch:
         description: '0search branch to deploy'
         default: 'staging'
         required: false
         type: string
       gosdk_branch:
         description: 'gosdk branch to inject into the CLIs'
         default: 'NOT OVERRIDDEN'
         required: false
         type: string
       skip_tests:
        description: '(LAST RESORT ONLY) Skip system tests. This will allow a PR to merge without requiring a green test run.  *By using you certify that the code being merged is not causing system tests to fail*'
        default: 'FALSE'
        required: false
        type: string
jobs:
  system-tests:
    timeout-minutes: 90
    runs-on: [ tests-suite ]
    steps:

    - uses: actions/checkout@v2

    - name: "Setup Test Run"
      run: |
        unset SHORT_SHA
        unset PR_ID
        unset TAG
        unset MERGE_SHORT_SHA

        echo "NETWORK_URL=$(echo dev-${RUNNER_NAME:(-1)}.devnet-0chain.net)" >> $GITHUB_ENV
        echo "RUNNER_NUMBER=${RUNNER_NAME:(-1)}" >> $GITHUB_ENV

        echo "GOSDK_SHA=NONE" >> $GITHUB_ENV
        if [ "${{ inputs.gosdk_branch }}" != "NOT OVERRIDDEN" ]; then
           echo "GOSDK_SHA=$(curl --silent --fail -u ${{ secrets.SVC_ACCOUNT_SECRET }}:x-oauth-basic https://api.github.com/repos/0chain/gosdk/git/refs/heads/${{ inputs.gosdk_branch }} | jq --raw-output .object.sha)" >> $GITHUB_ENV
        fi
        echo '#!/bin/bash

        echo
        echo "========================================================================"
        echo "Finding [$3] docker image for branch [$2]..."
        echo "========================================================================"

        if [[ "$2" == "master" ]]; then
          echo "Docker image [latest] found"
          echo "$(echo $3 | tr 0 Z | awk '"'"'{ print toupper($0) }'"'"')_TAG=latest" >> $GITHUB_ENV
          exit 0
        fi

        if [[ "$2" == "staging" ]]; then
          echo "Docker image [staging] found"
          echo "$(echo $3 | tr 0 Z | awk '"'"'{ print toupper($0) }'"'"')_TAG=staging" >> $GITHUB_ENV
          exit 0
        fi

        exit_code=0
        SHORT_SHA=$(curl --silent -u ${{ secrets.SVC_ACCOUNT_SECRET }}:x-oauth-basic https://api.github.com/repos/0chain/$1/git/refs/heads/$2 | jq --raw-output .object.sha | head -c 8)
        TAG=$(echo $2 | sed '"'"'s/\//-/g'"'"')

        echo "Searching for image [${TAG}-${SHORT_SHA}]..."
        docker pull 0chaindev/$3:${TAG}-${SHORT_SHA} > /dev/null 2>&1 || exit_code=$?

        if [[ $exit_code == 0 ]];then
          echo "Docker image [${TAG}-${SHORT_SHA}] found"
          echo "$(echo $3 | tr 0 Z | awk '"'"'{ print toupper($0) }'"'"')_TAG=${TAG}-${SHORT_SHA}" >> $GITHUB_ENV
          exit 0
        fi

        PR_ID=$(curl --silent -u ${{ secrets.SVC_ACCOUNT_SECRET }}:x-oauth-basic https://api.github.com/search/issues?q=is:pr+org:0chain+sha:$SHORT_SHA | jq --raw-output .items[0].number)
        if [[ -z "$PR_ID" || "$PR_ID" == "null" ]];then
          echo "::error title=$3 docker image not found::$3 docker image could not be found with tag [${TAG}-${SHORT_SHA}] and PR is not open. Please publish image manually at https://github.com/0chain/$1/actions/workflows/build-&-publish-docker-image.yml and try again"
          exit 1
        fi


        exit_code=0

        echo "Searching for image [pr-$PR_ID-$SHORT_SHA]..."
        docker pull 0chaindev/$3:pr-$PR_ID-$SHORT_SHA > /dev/null 2>&1 || exit_code=$?
        if [[ $exit_code == 0 ]];then
            echo "Docker image [pr-$PR_ID-$SHORT_SHA] found"
            echo "$(echo $3 | tr 0 Z | awk '"'"'{ print toupper($0) }'"'"')_TAG=pr-$PR_ID-$SHORT_SHA" >> $GITHUB_ENV
            exit 0
        fi

        exit_code=0
        MERGE_SHORT_SHA=$(curl --silent -u ${{ secrets.SVC_ACCOUNT_SECRET }}:x-oauth-basic https://api.github.com/repos/0chain/$1/pulls/$PR_ID | jq --raw-output .merge_commit_sha | head -c 8)

        if [[ -z "$MERGE_SHORT_SHA" || "$MERGE_SHORT_SHA" == "null" ]];then
          echo "::error title=$3 docker image not found::$3 docker image could not be found with tag [pr-$PR_ID-$SHORT_SHA] and PR merge commit not found. Please publish image manually at https://github.com/0chain/$1/actions/workflows/build-&-publish-docker-image.yml and try again"
          exit 1
        fi

        echo "Searching for image [merge-$MERGE_SHORT_SHA]..."
        docker pull 0chaindev/$3:merge-$MERGE_SHORT_SHA > /dev/null 2>&1 || exit_code=$?
        if [[ $exit_code == 0 ]];then
            echo "Docker image [merge-$MERGE_SHORT_SHA] found"
            echo "$(echo $3 | tr 0 Z | awk '"'"'{ print toupper($0) }'"'"')_TAG=merge-$MERGE_SHORT_SHA" >> $GITHUB_ENV
            exit 0
        fi

        echo "::error title=$3 docker image not found::$3 docker image could not be found with tags [${TAG}-${SHORT_SHA}], [pr-$PR_ID-$SHORT_SHA] or [merge-$MERGE_SHORT_SHA]. Please publish image manually at https://github.com/0chain/$1/actions/workflows/build-&-publish-docker-image.yml and try again"
        exit 1;

        ' > ./get_tag.sh;
        chmod 777 ./get_tag.sh;

    - name: "Check docker images have been published"
      if: ${{ inputs.skip_tests == 'FALSE' }}
      run: |
        ./get_tag.sh 0chain ${{ inputs.miner_branch }} miner
        ./get_tag.sh 0chain ${{ inputs.sharder_branch }} sharder
        ./get_tag.sh blobber ${{ inputs.blobber_branch }} blobber
        ./get_tag.sh blobber ${{ inputs.validator_branch }} validator
        ./get_tag.sh token_bridge_authserver ${{ inputs.authorizer_branch }} authorizer
        ./get_tag.sh 0box ${{ inputs.zbox_branch }} 0box
        ./get_tag.sh 0block ${{ inputs.zblock_branch }} 0block
        ./get_tag.sh 0dns ${{ inputs.zdns_branch }} 0dns
        ./get_tag.sh block-explorer ${{ inputs.explorer_branch }} explorer
        ./get_tag.sh 0proxy ${{ inputs.zproxy_branch }} 0proxy
        ./get_tag.sh 0search ${{ inputs.zsearch_branch }} 0search

    - name: "Set PR status as pending"
      uses: 0chain/actions/notify-pull-request@master
      continue-on-error: true
      with:
        state: "pending"
        message: "manual run against [${{ inputs.system_tests_branch }}] tests"
        system_tests_branch: ${{ inputs.system_tests_branch }}
        zbox_cli_branch: ${{ inputs.zbox_cli_branch }}
        zwallet_cli_branch: ${{ inputs.zwallet_cli_branch }}
        zerochain_branch: ${{ inputs.miner_branch }}
        blobber_branch: ${{ inputs.blobber_branch }}
        gosdk_branch: ${{ inputs.gosdk_branch }}
        zbox_branch: ${{ inputs.zbox_branch }}
        zblock_branch: ${{ inputs.zblock_branch }}
        zdns_branch: ${{ inputs.zdns_branch }}
        explorer_branch: ${{ inputs.explorer_branch }}
        zproxy_branch: ${{ inputs.zproxy_branch }}
        zsearch_branch: ${{ inputs.zsearch_branch }}
        authorizer_branch: ${{ inputs.authorizer_branch }}
        skip_tests: ${{ inputs.skip_tests }}
        github_token: ${{ secrets.SVC_ACCOUNT_SECRET }}

    - name: "Deploy 0Chain"
      if: ${{ inputs.skip_tests == 'FALSE' }}
      uses: 0chain/actions/deploy-0chain@master
      with:
        kube_config: ${{ secrets[format('DEV{0}KC', env.RUNNER_NUMBER)] }}
        teardown_condition: "TESTS_PASSED"
        miner_image:  ${{ env.MINER_TAG }}
        sharder_image: ${{ env.SHARDER_TAG }}
        blobber_image: ${{ env.BLOBBER_TAG }}
        validator_image: ${{ env.VALIDATOR_TAG }}
        authorizer_image: ${{ env.AUTHORIZER_TAG }}
        zbox_image: ${{ env.ZBOX_TAG }}
        zblock_image: ${{ env.ZBLOCK_TAG }}
        zdns_image: ${{ env.ZDNS_TAG }}
        explorer_image: ${{ env.EXPLORER_TAG }}
        zproxy_image: ${{ env.ZPROXY_TAG }}
        zsearch_image: ${{ env.ZSEARCH_TAG }}
        blobber_stake_image: "state-changes-count-block"

    - name: "Run System tests"
      if: ${{ inputs.skip_tests == 'FALSE' }}
      uses: 0chain/actions/run-system-tests@master
      with:
        system_tests_branch: ${{ inputs.system_tests_branch }}
        network: ${{ env.NETWORK_URL }}
        zbox_cli_branch: ${{ inputs.zbox_cli_branch }}
        zwallet_cli_branch: ${{ inputs.zwallet_cli_branch }}
        custom_go_sdk_version: ${{ env.GOSDK_SHA }}
        smart_contract_owner_wallet_json: ${{ secrets.SMART_CONTRACT_OWNER_WALLET_JSON }}
        svc_account_secret: ${{ github.token }}
        deploy_report_page: false
        archive_results: true
        run_flaky_tests: false
        retry_failures: true

    - name: "Set PR status as ${{ job.status }}"
      if: ${{ success() || failure() || cancelled() }}
      uses: 0chain/actions/notify-pull-request@master
      continue-on-error: true
      with:
        state: ${{ job.status }}
        message: "manual run against [${{ inputs.system_tests_branch }}] tests"
        system_tests_branch: ${{ inputs.system_tests_branch }}
        zbox_cli_branch: ${{ inputs.zbox_cli_branch }}
        zwallet_cli_branch: ${{ inputs.zwallet_cli_branch }}
        zerochain_branch: ${{ inputs.miner_branch }}
        blobber_branch: ${{ inputs.blobber_branch }}
        gosdk_branch: ${{ inputs.gosdk_branch }}
        zbox_branch: ${{ inputs.zbox_branch }}
        zblock_branch: ${{ inputs.zblock_branch }}
        zdns_branch: ${{ inputs.zdns_branch }}
        explorer_branch: ${{ inputs.explorer_branch }}
        zproxy_branch: ${{ inputs.zproxy_branch }}
        zsearch_branch: ${{ inputs.zsearch_branch }}
        authorizer_branch: ${{ inputs.authorizer_branch }}
        skip_tests: ${{ inputs.skip_tests }}
        github_token: ${{ secrets.SVC_ACCOUNT_SECRET }}
