name: "Test"
on:
  push:
jobs:
  test:
    name: "Test Notify"
    runs-on: self-hosted
    steps:
    - name: "Get current PR"
      uses: jwalton/gh-find-current-pr@v1
      id: findPr
      with:
        github-token: ${{ github.token }}

    - name: "Set PR status as pending"
      uses: 0chain/actions/set-pr-status@feature/fix-pr-status
      if: steps.findPr.outputs.number && github.event.inputs.test_file_filter == ''
      with:
          pr_number: ${{ steps.findPr.outputs.pr }}
          description: "System tests running with default config..."
          state: "success"
          repository: ${{ github.repository }}
          status_name: "0Chain System Tests"
          target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          github_token:  ${{ github.token }}