name: UPDATE-TEST

on:
  workflow_dispatch:
    inputs:
      chainimage:
        description: '0chain image tag'
        required: true
        default: staging
      blobberimage:
        description: 'blobber image tag'
        required: true
        default: staging
      dnsimage:
        description: '0dns image tag'
        required: true
        default: staging
      blockimage:
        description: '0block image tag'
        required: true
        default: staging
      boximage:
        description: '0box image tag'
        required: true
        default: staging
      searchimage:
        description: '0search image tag'
        required: true
        default: staging
      proxyimage:
        description: '0proxy image tag'
        required: true
        default: staging
      explorerimage:
        description: 'explorer image tag'
        required: true
        default: staging
      blobberStackimage:
        description: 'blobberStack image tag'
        required: true
        default: latest



jobs:
  deploy:
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v1
        with:
          version: 'v3.2.2'
      - uses: azure/setup-kubectl@v1
        id: install
      - name: Setup helm repo
        run: |
          helm repo add 0chain-helm http://0chain-helm-chart.s3-website.us-east-2.amazonaws.com/staging/
          helm repo update
      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.TESTKC }}" | base64 -d > ~/.kube/config



      - name: Setup chain
        if: always()
        run: |
          helm upgrade --install --wait --timeout 120s 0chain -n test --set sharder.sharderImage.tag=${{ github.event.inputs.chainimage }} --set miner.minerImage.tag=${{ github.event.inputs.chainimage }} 0chain-helm/zchain
     
          helm upgrade --install --wait --timeout 120s 0dns -n test --set zdns.image.tag=${{ github.event.inputs.dnsimage }} --set zdns.host=test.0chain.net 0chain-helm/zdns

          helm upgrade --install --wait --timeout 120s blobber -n test --set blobber.blobberImage.tag=${{ github.event.inputs.blobberimage }} --set validator.validatorImage.tag=${{ github.event.inputs.blobberimage }} 0chain-helm/blobber

          helm upgrade --install --wait --timeout 120s 0block -n test --set block.blockImage.tag=${{ github.event.inputs.blockimage }} --set block.host=test.0chain.net 0chain-helm/zblock

          helm upgrade --install --wait --timeout 120s explorer -n test --set explorer.explorerImage.tag=${{ github.event.inputs.explorerimage }} --set explorer.host=test.0chain.net 0chain-helm/blockExplorer

          helm upgrade --install --wait --timeout 120s 0proxy -n test --set proxy.image.tag=${{ github.event.inputs.proxyimage }} --set proxy.host=test.0chain.net 0chain-helm/zproxy

          helm upgrade --install --wait --timeout 120s 0box -n test --set zbox.zboxImage.tag=${{ github.event.inputs.boximage }} --set zbox.host=test.0chain.net 0chain-helm/zbox

          helm upgrade --install --wait --timeout 120s 0search -n test --set blockRecorder.blockRecorderImage.tag=${{ github.event.inputs.searchimage }} --set blockRecorder.host=test.0chain.net 0chain-helm/zsearch

          helm upgrade --install --wait --timeout 120s blobber-stake -n test --set blobberStack.blobberCount=6 --set blobberStack.host=test.0chain.net --set blobberStack.image.tag=${{ github.event.inputs.blobberStackimage }} 0chain-helm/blobberStake

          rm -rf ~/.kube
